name: "CodeQL"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '19 5 * * 5'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]    
   
    steps:
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
    - name: Corp-quality
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
