- name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      
    - name: Corp-quality
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
